In [1]:
import cv2

In [47]:
im=cv2.imread("f:/ahmad.jpg")
im.ndim

3

In [83]:

for im in data:
    path=os.path.join('f:/Train',im)
    img=cv2.imread(path)
    face_cascade=cv2.CascadeClassifier("f://cascade.xml")
    gray_img=cv2.cvtColor(img,cv2.COLOR_BGRA2GRAY)
    faces=face_cascade.detectMultiScale(gray_img,scaleFactor=1.05,minNeighbors=5)
    for x,y,w,h in faces:
        img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),4)
        print(img.shape)
    resized=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
    cv2.imshow("gray",resized)
    cv2.waitKey(2000)
    cv2.destroyAllWindows()


(839, 529, 3)
(758, 520, 3)
(773, 593, 3)
(773, 593, 3)


error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [81]:
for x,y,w,h in faces:
    print(x+w)
    print(y+h)
    #print(w)
    #print(h)

542
531
419
685


In [68]:
faces

array([[477, 466,  65,  65],
       [242, 508, 177, 177]], dtype=int32)

-1

In [28]:
import os
import numpy as np

In [24]:
data=os.listdir('f:/images')

In [52]:
tr_data=[]
    tr_data.append([np.array(img_data)])
    
    
    

[[[  0 113 115]
  [  0 111 113]
  [ 14 108 113]
  ...
  [206 184 186]
  [208 184 186]
  [208 184 186]]

 [[  0 110 113]
  [  1 110 112]
  [ 16 108 113]
  ...
  [206 184 186]
  [208 184 186]
  [208 184 186]]

 [[  0 107 111]
  [  2 107 110]
  [ 18 106 112]
  ...
  [206 183 187]
  [208 183 187]
  [207 182 186]]

 ...

 [[ 92  89  84]
  [ 94  91  86]
  [ 96  93  88]
  ...
  [ 35  57  68]
  [ 28  55  65]
  [ 24  55  64]]

 [[ 91  88  83]
  [ 93  90  85]
  [ 96  93  88]
  ...
  [ 32  56  68]
  [ 28  56  67]
  [ 25  57  68]]

 [[ 90  87  82]
  [ 92  89  84]
  [ 96  93  88]
  ...
  [ 34  58  70]
  [ 30  60  71]
  [ 30  62  73]]]
